<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css"
          integrity="sha256-p4NxAoJBhIIN+hmNHrzRCf9tD/miZyoHS5obTRR9BMY=" crossorigin=""/>
    <script src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js"
            integrity="sha256-20nQCchB9co0qIjJZRGuk2/Z9VM+kNiyxNV1lvTlZBo=" crossorigin=""></script>
    <style>
    </style>
</head>
<body>

<!--<div id="map">-->

<!--</div>-->

<?php
$email = "varga@org.ocom";
var_dump(str_contains($email,'@org.com'));
?>
<!--<table>-->
<!--    <tr>-->
<!--        <td>-->
<!--            <form method="post">-->
<!--                 Select option -->
<!--                <select name="id_attraction" id="attraction_name" class="form-select">-->
<!--                    <option value="1">asd</option>-->
<!--                    <option value="2">ASD</option>-->
<!--                     Your options here -->
<!--                </select>-->
<!--        </td>-->
<!--        <td>-->
<!--            Edit button -->
<!--            <button class="border-1 btn btn-warning" type="submit" name='action' value='edit'>Edit</button>-->
<!--            <button class="border-1 btn btn-warning" type="submit" name='action' value='delete'>Delete</button>-->
<!--            </form>-->
<!--        </td>-->
<!--    </tr>-->
<!--     Additional rows generated by your loop -->
<!--</table>-->
</body>
<!--<script>-->
<!--    const map = L.map('map');-->
<!--    var title = "Eiffle toow";-->
<!---->
<!--    map.setView([48.804806, 2.120333], 12);-->
<!--    //48.804806, 2.120333-->
<!--    L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png', {-->
<!--        attribution: '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'-->
<!--    }).addTo(map);-->
<!---->
<!--    L.marker([48.804806, 2.120333]).bindPopup('<h3>'+ title + '</h3>')-->
<!--        .addTo(map);-->
<!---->
<!--</script>-->
</html>